FROM python:3.11-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV PYTHONPATH=$PYTHONPATH:./src

COPY requirements.txt .

RUN pip install -r requirements.txt

#! src files must be mounted to /app/src from the docker-compose.yml file

# todo: add alembic
CMD alembic upgrade head 

CMD uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
