"""wallet_chain_family

Revision ID: 05ea3e73778d
Revises: d39ba5821566
Create Date: 2025-06-27 17:21:17.543148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05ea3e73778d'
down_revision: Union[str, None] = 'd39ba5821566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('EVM', 'SOLANA', name='chainfamily').create(op.get_bind())
    op.drop_index(op.f('ix_project_engagement_id'), table_name='project_engagement')
    op.drop_table('project_engagement')
    op.add_column('wallet_address', sa.Column('chain_family', postgresql.ENUM('EVM', 'SOLANA', name='chainfamily', create_type=False), server_default='EVM', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallet_address', 'chain_family')
    op.create_table('project_engagement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('social_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('engagement', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reposts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('project_engagement_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_account.id'], name=op.f('project_engagement_social_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('project_engagement_pkey'))
    )
    op.create_index(op.f('ix_project_engagement_id'), 'project_engagement', ['id'], unique=False)
    sa.Enum('EVM', 'SOLANA', name='chainfamily').drop(op.get_bind())
    # ### end Alembic commands ###
