"""chat_models

Revision ID: 0cf278522a91
Revises: 619f0d76a59d
Create Date: 2025-03-24 07:01:30.023025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0cf278522a91'
down_revision: Union[str, None] = '619f0d76a59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='model').create(op.get_bind(), checkfirst=True)
    sa.Enum('OPENAI', 'ANTHROPIC', 'GEMINI', 'GROQ', 'CLAUDE', name='service').create(op.get_bind(), checkfirst=True)
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='role').create(op.get_bind(), checkfirst=True)
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role', create_type=False), nullable=False),
    sa.Column('recipient', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role', create_type=False), nullable=False),
    sa.Column('service', postgresql.ENUM('OPENAI', 'ANTHROPIC', 'GEMINI', 'GROQ', 'CLAUDE', name='service', create_type=False), nullable=False),
    sa.Column('model', postgresql.ENUM('GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='model', create_type=False), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat')
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='role').drop(op.get_bind(), checkfirst=True)
    sa.Enum('OPENAI', 'ANTHROPIC', 'GEMINI', 'GROQ', 'CLAUDE', name='service').drop(op.get_bind(), checkfirst=True)
    sa.Enum('GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='model').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
