"""add_autoyaps_and_settings_and_ondelete_to_all_models

Revision ID: 11a8b608d44c
Revises: 6eec2a3c613f
Create Date: 2025-05-28 04:12:22.232453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11a8b608d44c'
down_revision: Union[str, None] = '6eec2a3c613f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('post_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_template_id'), 'post_template', ['id'], unique=False)
    op.drop_constraint(op.f('chat_user_id_fkey'), 'chat', type_='foreignkey')
    op.create_foreign_key(None, 'chat', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('message_chat_id_fkey'), 'message', type_='foreignkey')
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_account_status_project_id_fkey'), 'project_account_status', type_='foreignkey')
    op.drop_constraint(op.f('project_account_status_account_id_fkey'), 'project_account_status', type_='foreignkey')
    op.create_foreign_key(None, 'project_account_status', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_account_status', 'social_account', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_mention_project_id_fkey'), 'project_mention', type_='foreignkey')
    op.drop_constraint(op.f('project_mention_post_id_fkey'), 'project_mention', type_='foreignkey')
    op.create_foreign_key(None, 'project_mention', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_mention', 'social_post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('promo_code_usage_user_id_fkey'), 'promo_code_usage', type_='foreignkey')
    op.drop_constraint(op.f('promo_code_usage_promo_code_id_fkey'), 'promo_code_usage', type_='foreignkey')
    op.create_foreign_key(None, 'promo_code_usage', 'promo_code', ['promo_code_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'promo_code_usage', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('social_post_account_id_fkey'), 'social_post', type_='foreignkey')
    op.create_foreign_key(None, 'social_post', 'social_account', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('social_post_statistic_post_id_fkey'), 'social_post_statistic', type_='foreignkey')
    op.create_foreign_key(None, 'social_post_statistic', 'social_post', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('user', sa.Column('personalization_brain_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('user_fact_user_id_fkey'), 'user_fact', type_='foreignkey')
    op.create_foreign_key(None, 'user_fact', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_selected_project_user_id_fkey'), 'user_selected_project', type_='foreignkey')
    op.drop_constraint(op.f('user_selected_project_project_id_fkey'), 'user_selected_project', type_='foreignkey')
    op.create_foreign_key(None, 'user_selected_project', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_selected_project', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wallet_address_user_id_fkey'), 'wallet_address', type_='foreignkey')
    op.create_foreign_key(None, 'wallet_address', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet_address', type_='foreignkey')
    op.create_foreign_key(op.f('wallet_address_user_id_fkey'), 'wallet_address', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_selected_project', type_='foreignkey')
    op.drop_constraint(None, 'user_selected_project', type_='foreignkey')
    op.create_foreign_key(op.f('user_selected_project_project_id_fkey'), 'user_selected_project', 'project', ['project_id'], ['id'])
    op.create_foreign_key(op.f('user_selected_project_user_id_fkey'), 'user_selected_project', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_fact', type_='foreignkey')
    op.create_foreign_key(op.f('user_fact_user_id_fkey'), 'user_fact', 'user', ['user_id'], ['id'])
    op.drop_column('user', 'personalization_brain_settings')
    op.drop_constraint(None, 'social_post_statistic', type_='foreignkey')
    op.create_foreign_key(op.f('social_post_statistic_post_id_fkey'), 'social_post_statistic', 'social_post', ['post_id'], ['id'])
    op.drop_constraint(None, 'social_post', type_='foreignkey')
    op.create_foreign_key(op.f('social_post_account_id_fkey'), 'social_post', 'social_account', ['account_id'], ['id'])
    op.drop_constraint(None, 'promo_code_usage', type_='foreignkey')
    op.drop_constraint(None, 'promo_code_usage', type_='foreignkey')
    op.create_foreign_key(op.f('promo_code_usage_promo_code_id_fkey'), 'promo_code_usage', 'promo_code', ['promo_code_id'], ['id'])
    op.create_foreign_key(op.f('promo_code_usage_user_id_fkey'), 'promo_code_usage', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'project_mention', type_='foreignkey')
    op.drop_constraint(None, 'project_mention', type_='foreignkey')
    op.create_foreign_key(op.f('project_mention_post_id_fkey'), 'project_mention', 'social_post', ['post_id'], ['id'])
    op.create_foreign_key(op.f('project_mention_project_id_fkey'), 'project_mention', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_account_status', type_='foreignkey')
    op.drop_constraint(None, 'project_account_status', type_='foreignkey')
    op.create_foreign_key(op.f('project_account_status_account_id_fkey'), 'project_account_status', 'social_account', ['account_id'], ['id'])
    op.create_foreign_key(op.f('project_account_status_project_id_fkey'), 'project_account_status', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.create_foreign_key(op.f('message_chat_id_fkey'), 'message', 'chat', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.create_foreign_key(op.f('chat_user_id_fkey'), 'chat', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_post_template_id'), table_name='post_template')
    op.drop_table('post_template')
    # ### end Alembic commands ###
