"""project_min_likes_personal

Revision ID: 1d77903a1582
Revises: 22481045ef42
Create Date: 2025-06-17 04:14:16.889451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d77903a1582'
down_revision: Union[str, None] = '22481045ef42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('search_min_likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'search_min_likes')
    # ### end Alembic commands ###
