"""leaderboard_period

Revision ID: 22481045ef42
Revises: 58933bbb4e6f
Create Date: 2025-06-11 22:42:07.539960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22481045ef42'
down_revision: Union[str, None] = '58933bbb4e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_leaderboard_history', sa.Column('start_ts', sa.Integer(), nullable=False))
    op.add_column('project_leaderboard_history', sa.Column('end_ts', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_leaderboard_history', 'end_ts')
    op.drop_column('project_leaderboard_history', 'start_ts')
    # ### end Alembic commands ###
