"""Add last_analysed_nonce to Chat model

Revision ID: 228709cc74f1
Revises: be2973e4f768
Create Date: 2025-04-18 06:46:30.586997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228709cc74f1'
down_revision: Union[str, None] = 'be2973e4f768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('last_analysed_nonce', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'last_analysed_nonce')
    # ### end Alembic commands ###
