"""added_project_icon_url

Revision ID: 2c77f576da2c
Revises: dd4ea126bcc8
Create Date: 2025-06-04 11:18:07.477979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c77f576da2c'
down_revision: Union[str, None] = 'dd4ea126bcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('icon_url', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'icon_url')
    # ### end Alembic commands ###
