"""plan_check

Revision ID: 34daebed5a38
Revises: 05ea3e73778d
Create Date: 2025-07-01 12:19:41.910906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34daebed5a38'
down_revision: Union[str, None] = '05ea3e73778d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('BASIC', 'PRO', 'ULTRA', name='subscriptionplantype').create(op.get_bind())
    op.create_table('user_plan_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('user_plan', postgresql.ENUM('BASIC', 'PRO', 'ULTRA', name='subscriptionplantype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plan_check_id'), 'user_plan_check', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_plan_check_id'), table_name='user_plan_check')
    op.drop_table('user_plan_check')
    sa.Enum('BASIC', 'PRO', 'ULTRA', name='subscriptionplantype').drop(op.get_bind())
    # ### end Alembic commands ###
