"""add_leaderboar_projects

Revision ID: 3adb9e6faeed
Revises: 209eda1d310b
Create Date: 2025-07-25 11:53:17.159449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import time


# revision identifiers, used by Alembic.
revision: str = '3adb9e6faeed'
down_revision: Union[str, None] = '209eda1d310b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Получаем текущее время как timestamp
    now_timestamp = int(time.time())
    
    # 1. Добавляем проект Morph (если его нет)
    op.execute(f"""
        INSERT INTO project (created_at, name, description, url, icon_url, keywords, search_min_likes, is_selected_by_default, is_leaderboard_project)
        SELECT {now_timestamp}, 'Morph', NULL, 'https://www.morphl2.io/', '', 'MorphLayer;@MorphLayer', 0, FALSE, TRUE
        WHERE NOT EXISTS (
            SELECT 1 FROM project WHERE name = 'Morph'
        );
    """)
    
    # 2. Добавляем социальный аккаунт @MorphLayer (если его нет)
    op.execute(f"""
        INSERT INTO social_account (created_at, social_id, social_login, name, twitter_scout_score, twitter_scout_score_updated_at, last_avatar_url, last_followers_count, is_disabled_for_leaderboard)
        SELECT {now_timestamp}, '', 'MorphLayer', 'Morph', NULL, NULL, NULL, NULL, FALSE
        WHERE NOT EXISTS (
            SELECT 1 FROM social_account WHERE social_login = 'MorphLayer'
        );
    """)
    
    # 3. Создаем связь между проектом Morph и аккаунтом MorphLayer как MEDIA (если ее нет)
    op.execute(f"""
        INSERT INTO project_account_status (created_at, project_id, account_id, type)
        SELECT {now_timestamp}, p.id, s.id, 'MEDIA'
        FROM project p, social_account s
        WHERE p.name = 'Morph' AND s.social_login = 'MorphLayer'
        AND NOT EXISTS (
            SELECT 1 FROM project_account_status pas
            WHERE pas.project_id = p.id AND pas.account_id = s.id
        );
    """)
    
    # 4. Добавляем проект ProjectOasis (если его нет)
    op.execute(f"""
        INSERT INTO project (created_at, name, description, url, icon_url, keywords, search_min_likes, is_selected_by_default, is_leaderboard_project)
        SELECT {now_timestamp}, 'ProjectOasis', NULL, 'https://projectoasis.medium.com/', 'https://assets.coingecko.com/coins/images/18755/standard/Oasis_Logo_1.2%28scaled%29.png?1696518220', '@ProjectOasis_', 0, FALSE, TRUE
        WHERE NOT EXISTS (
            SELECT 1 FROM project WHERE name = 'ProjectOasis'
        );
    """)
    
    # 5. Добавляем социальный аккаунт @ProjectOasis_ (если его нет)
    op.execute(f"""
        INSERT INTO social_account (created_at, social_id, social_login, name, twitter_scout_score, twitter_scout_score_updated_at, last_avatar_url, last_followers_count, is_disabled_for_leaderboard)
        SELECT {now_timestamp}, '', 'ProjectOasis_', 'ProjectOasis', NULL, NULL, NULL, NULL, FALSE
        WHERE NOT EXISTS (
            SELECT 1 FROM social_account WHERE social_login = 'ProjectOasis_'
        );
    """)
    
    # 6. Создаем связь между проектом ProjectOasis и аккаунтом ProjectOasis_ как MEDIA (если ее нет)
    op.execute(f"""
        INSERT INTO project_account_status (created_at, project_id, account_id, type)
        SELECT {now_timestamp}, p.id, s.id, 'MEDIA'
        FROM project p, social_account s
        WHERE p.name = 'ProjectOasis' AND s.social_login = 'ProjectOasis_'
        AND NOT EXISTS (
            SELECT 1 FROM project_account_status pas
            WHERE pas.project_id = p.id AND pas.account_id = s.id
        );
    """)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Даунгрейд не должен ничего удалять по требованию
    pass
    # ### end Alembic commands ###
