"""payouts_stats

Revision ID: 43aab69915c3
Revises: f4295a37a89c
Create Date: 2025-06-18 14:52:47.245284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aab69915c3'
down_revision: Union[str, None] = 'f4295a37a89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_payout', sa.Column('new_posts_count', sa.Integer(), nullable=True))
    op.add_column('score_payout', sa.Column('first_post_at', sa.Integer(), nullable=True))
    op.add_column('score_payout', sa.Column('last_post_at', sa.Integer(), nullable=True))
    op.add_column('score_payout', sa.Column('weekly_streak_start_at', sa.Integer(), nullable=True))
    op.add_column('score_payout', sa.Column('loyalty_points', sa.Integer(), nullable=True))
    op.add_column('score_payout', sa.Column('min_loyalty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_payout', 'min_loyalty')
    op.drop_column('score_payout', 'loyalty_points')
    op.drop_column('score_payout', 'weekly_streak_start_at')
    op.drop_column('score_payout', 'last_post_at')
    op.drop_column('score_payout', 'first_post_at')
    op.drop_column('score_payout', 'new_posts_count')
    # ### end Alembic commands ###
