"""reinit

Revision ID: 4984298fed48
Revises: 
Create Date: 2025-05-09 04:27:59.572371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4984298fed48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='role').create(op.get_bind())
    sa.Enum('TEXT', 'TOOL_CALL', 'IMAGE', 'AUDIO', 'VIDEO', 'FILE', 'LOCATION', 'TRANSACTION', name='messagetype').create(op.get_bind())
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('preferred_name', sa.String(length=20), nullable=True),
    sa.Column('user_context', sa.String(length=500), nullable=True),
    sa.Column('chat_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('credits_last_update', sa.Integer(), nullable=False),
    sa.CheckConstraint('credits >= 0', name='credits_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('last_analysed_nonce', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('user_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fact_id'), 'user_fact', ['id'], unique=False)
    op.create_table('wallet_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_wallet_address_id'), 'wallet_address', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('TEXT', 'TOOL_CALL', 'IMAGE', 'AUDIO', 'VIDEO', 'FILE', 'LOCATION', 'TRANSACTION', name='messagetype', create_type=False), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sender', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role', create_type=False), nullable=False),
    sa.Column('recipient', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role', create_type=False), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.Integer(), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_wallet_address_id'), table_name='wallet_address')
    op.drop_table('wallet_address')
    op.drop_index(op.f('ix_user_fact_id'), table_name='user_fact')
    op.drop_table('user_fact')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    sa.Enum('TEXT', 'TOOL_CALL', 'IMAGE', 'AUDIO', 'VIDEO', 'FILE', 'LOCATION', 'TRANSACTION', name='messagetype').drop(op.get_bind())
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='role').drop(op.get_bind())
    # ### end Alembic commands ###
