"""leaderboard

Revision ID: 58933bbb4e6f
Revises: 7b979fe2a527
Create Date: 2025-06-11 21:51:04.840272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58933bbb4e6f'
down_revision: Union[str, None] = '7b979fe2a527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_engagement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('engagement', sa.Float(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_engagement_id'), 'project_engagement', ['id'], unique=False)
    op.create_table('project_leaderboard_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_leaderboard_history_id'), 'project_leaderboard_history', ['id'], unique=False)
    op.create_table('score_payout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('social_account_id', sa.Integer(), nullable=False),
    sa.Column('project_leaderboard_history_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('engagement', sa.Float(), nullable=False),
    sa.Column('mindshare', sa.Float(), nullable=False),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_leaderboard_history_id'], ['project_leaderboard_history.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_payout_id'), 'score_payout', ['id'], unique=False)
    op.add_column('project', sa.Column('is_leaderboard_project', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('social_account', sa.Column('twitter_scout_score', sa.Float(), nullable=True))
    op.add_column('social_account', sa.Column('twitter_scout_score_updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_account', 'twitter_scout_score_updated_at')
    op.drop_column('social_account', 'twitter_scout_score')
    op.drop_column('project', 'is_leaderboard_project')
    op.drop_index(op.f('ix_score_payout_id'), table_name='score_payout')
    op.drop_table('score_payout')
    op.drop_index(op.f('ix_project_leaderboard_history_id'), table_name='project_leaderboard_history')
    op.drop_table('project_leaderboard_history')
    op.drop_index(op.f('ix_project_engagement_id'), table_name='project_engagement')
    op.drop_table('project_engagement')
    # ### end Alembic commands ###
