"""init

Revision ID: 5f1c0d51a8b9
Revises: 
Create Date: 2025-03-26 13:57:17.247073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f1c0d51a8b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='role').create(op.get_bind())
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='chatdetailslevel').create(op.get_bind())
    sa.Enum('FORMAL', 'INFORMAL', name='chatstyle').create(op.get_bind())
    sa.Enum('GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='model').create(op.get_bind())
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('chain_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('preferred_name', sa.String(length=20), nullable=True),
    sa.Column('user_context', sa.String(length=500), nullable=True),
    sa.Column('preferred_chat_model', postgresql.ENUM('GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='model', create_type=False), nullable=True),
    sa.Column('preferred_chat_style', postgresql.ENUM('FORMAL', 'INFORMAL', name='chatstyle', create_type=False), nullable=True),
    sa.Column('preferred_chat_details_level', postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='chatdetailslevel', create_type=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sender', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role', create_type=False), nullable=True),
    sa.Column('recipient', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='role', create_type=False), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('model', postgresql.ENUM('GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='model', create_type=False), nullable=True),
    sa.Column('chat_style', postgresql.ENUM('FORMAL', 'INFORMAL', name='chatstyle', create_type=False), nullable=True),
    sa.Column('chat_details_level', postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='chatdetailslevel', create_type=False), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('selected_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    sa.Enum('GPT_4', 'GPT_4O', 'GPT_4O_MINI', name='model').drop(op.get_bind())
    sa.Enum('FORMAL', 'INFORMAL', name='chatstyle').drop(op.get_bind())
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='chatdetailslevel').drop(op.get_bind())
    sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='role').drop(op.get_bind())
    # ### end Alembic commands ###
