"""user_pro_promo

Revision ID: 622606839db3
Revises: 4984298fed48
Create Date: 2025-05-12 14:51:37.747437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622606839db3'
down_revision: Union[str, None] = '4984298fed48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pro_plan_promo_activated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pro_plan_promo_activated')
    # ### end Alembic commands ###
