"""added_promo_code

Revision ID: 6893fd8d0650
Revises: 622606839db3
Create Date: 2025-05-14 17:02:11.611337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6893fd8d0650'
down_revision: Union[str, None] = '622606839db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_promo_code_id'), 'promo_code', ['id'], unique=False)
    op.create_table('promo_code_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_code_usage_id'), 'promo_code_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_code_usage_id'), table_name='promo_code_usage')
    op.drop_table('promo_code_usage')
    op.drop_index(op.f('ix_promo_code_id'), table_name='promo_code')
    op.drop_table('promo_code')
    # ### end Alembic commands ###
