"""admin_user

Revision ID: 6eec2a3c613f
Revises: bff0eba4231d
Create Date: 2025-05-26 08:06:04.131385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eec2a3c613f'
down_revision: Union[str, None] = 'bff0eba4231d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'MODERATOR', name='admin_role').create(op.get_bind())
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MODERATOR', name='admin_role', create_type=False), server_default='ADMIN', nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_id'), 'admin_user', ['id'], unique=False)
    op.create_index(op.f('ix_admin_user_login'), 'admin_user', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_user_login'), table_name='admin_user')
    op.drop_index(op.f('ix_admin_user_id'), table_name='admin_user')
    op.drop_table('admin_user')
    sa.Enum('ADMIN', 'MODERATOR', name='admin_role').drop(op.get_bind())
    # ### end Alembic commands ###
