"""soc_acc_leaderboard_block

Revision ID: 9686ef605434
Revises: 24907650e432
Create Date: 2025-06-19 11:24:33.954278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9686ef605434'
down_revision: Union[str, None] = '24907650e432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_account', sa.Column('is_disabled_for_leaderboard', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_account', 'is_disabled_for_leaderboard')
    # ### end Alembic commands ###
