"""new_leaderboards_prodjects_2

Revision ID: 9ca43bdfc4db
Revises: 9e13e1e0a096
Create Date: 2025-08-02 15:54:49.692533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import time


# revision identifiers, used by Alembic.
revision: str = '9ca43bdfc4db'
down_revision: Union[str, None] = '9e13e1e0a096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    now_timestamp = int(time.time())

    # 1. Add SuperVerse project
    op.execute(f"""
        INSERT INTO project (created_at, name, description, url, icon_url, keywords, search_min_likes, is_selected_by_default, is_leaderboard_project)
        SELECT {now_timestamp}, 'SuperVerse', NULL, 'https://www.superverse.co/', 'https://s2.coinmarketcap.com/static/img/coins/64x64/8290.png', 'SuperVerse;@SuperVerse', 0, FALSE, TRUE
        WHERE NOT EXISTS (SELECT 1 FROM project WHERE name = 'SuperVerse');
    """)

    # 2. Add SuperVerse social account
    op.execute(f"""
        INSERT INTO social_account (created_at, social_id, social_login, name, twitter_scout_score, twitter_scout_score_updated_at, last_avatar_url, last_followers_count, is_disabled_for_leaderboard)
        SELECT {now_timestamp}, '', 'SuperVerse', 'SuperVerse', NULL, NULL, NULL, NULL, FALSE
        WHERE NOT EXISTS (SELECT 1 FROM social_account WHERE social_login = 'SuperVerse');
    """)

    # 3. Link SuperVerse project and account
    op.execute(f"""
        INSERT INTO project_account_status (created_at, project_id, account_id, type)
        SELECT {now_timestamp}, p.id, s.id, 'MEDIA'
        FROM project p, social_account s
        WHERE p.name = 'SuperVerse' AND s.social_login = 'SuperVerse'
        AND NOT EXISTS (
            SELECT 1 FROM project_account_status pas
            WHERE pas.project_id = p.id AND pas.account_id = s.id
        );
    """)

    # 4. Add BlackholeDex project
    op.execute(f"""
        INSERT INTO project (created_at, name, description, url, icon_url, keywords, search_min_likes, is_selected_by_default, is_leaderboard_project)
        SELECT {now_timestamp}, 'BlackholeDex', NULL, 'https://blackhole.xyz/', 'https://s2.coinmarketcap.com/static/img/coins/64x64/37396.png', 'Blackhole Dex;blackhole.xyz;@BlackholeDex', 0, FALSE, TRUE
        WHERE NOT EXISTS (SELECT 1 FROM project WHERE name = 'BlackholeDex');
    """)

    # 5. Add BlackholeDex social account
    op.execute(f"""
        INSERT INTO social_account (created_at, social_id, social_login, name, twitter_scout_score, twitter_scout_score_updated_at, last_avatar_url, last_followers_count, is_disabled_for_leaderboard)
        SELECT {now_timestamp}, '', 'BlackholeDex', 'BlackholeDex', NULL, NULL, NULL, NULL, FALSE
        WHERE NOT EXISTS (SELECT 1 FROM social_account WHERE social_login = 'BlackholeDex');
    """)

    # 6. Link BlackholeDex project and account
    op.execute(f"""
        INSERT INTO project_account_status (created_at, project_id, account_id, type)
        SELECT {now_timestamp}, p.id, s.id, 'MEDIA'
        FROM project p, social_account s
        WHERE p.name = 'BlackholeDex' AND s.social_login = 'BlackholeDex'
        AND NOT EXISTS (
            SELECT 1 FROM project_account_status pas
            WHERE pas.project_id = p.id AND pas.account_id = s.id
        );
    """)

    # 7. Add Intuition project
    op.execute(f"""
        INSERT INTO project (created_at, name, description, url, icon_url, keywords, search_min_likes, is_selected_by_default, is_leaderboard_project)
        SELECT {now_timestamp}, 'Intuition', NULL, 'https://intuition.systems/', '', '@0xIntuition', 0, FALSE, TRUE
        WHERE NOT EXISTS (SELECT 1 FROM project WHERE name = 'Intuition');
    """)

    # 8. Add Intuition social account
    op.execute(f"""
        INSERT INTO social_account (created_at, social_id, social_login, name, twitter_scout_score, twitter_scout_score_updated_at, last_avatar_url, last_followers_count, is_disabled_for_leaderboard)
        SELECT {now_timestamp}, '', '0xIntuition', 'Intuition', NULL, NULL, NULL, NULL, FALSE
        WHERE NOT EXISTS (SELECT 1 FROM social_account WHERE social_login = '0xIntuition');
    """)

    # 9. Link Intuition project and account
    op.execute(f"""
        INSERT INTO project_account_status (created_at, project_id, account_id, type)
        SELECT {now_timestamp}, p.id, s.id, 'MEDIA'
        FROM project p, social_account s
        WHERE p.name = 'Intuition' AND s.social_login = '0xIntuition'
        AND NOT EXISTS (
            SELECT 1 FROM project_account_status pas
            WHERE pas.project_id = p.id AND pas.account_id = s.id
        );
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
