"""remove_user_chainid

Revision ID: be2973e4f768
Revises: 73f2f6b291d5
Create Date: 2025-04-16 17:22:07.877313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2973e4f768'
down_revision: Union[str, None] = '73f2f6b291d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'chain_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chain_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
