"""auto_yaps

Revision ID: bff0eba4231d
Revises: ee003ec8b942
Create Date: 2025-05-23 13:31:30.641837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bff0eba4231d'
down_revision: Union[str, None] = 'ee003ec8b942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MEDIA', 'FOUNDER', name='projectaccountstatustype').create(op.get_bind())
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('social_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(), nullable=False),
    sa.Column('social_login', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_account_id'), 'social_account', ['id'], unique=False)
    op.create_table('project_account_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('type', postgresql.ENUM('MEDIA', 'FOUNDER', name='projectaccountstatustype', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['social_account.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_account_status_id'), 'project_account_status', ['id'], unique=False)
    op.create_table('social_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('posted_at', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['social_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_id'), 'social_post', ['id'], unique=False)
    op.create_table('user_selected_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_selected_project_id'), 'user_selected_project', ['id'], unique=False)
    op.create_table('project_mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_post.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_mention_id'), 'project_mention', ['id'], unique=False)
    op.create_table('social_post_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_statistic_id'), 'social_post_statistic', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_post_statistic_id'), table_name='social_post_statistic')
    op.drop_table('social_post_statistic')
    op.drop_index(op.f('ix_project_mention_id'), table_name='project_mention')
    op.drop_table('project_mention')
    op.drop_index(op.f('ix_user_selected_project_id'), table_name='user_selected_project')
    op.drop_table('user_selected_project')
    op.drop_index(op.f('ix_social_post_id'), table_name='social_post')
    op.drop_table('social_post')
    op.drop_index(op.f('ix_project_account_status_id'), table_name='project_account_status')
    op.drop_table('project_account_status')
    op.drop_index(op.f('ix_social_account_id'), table_name='social_account')
    op.drop_table('social_account')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    sa.Enum('MEDIA', 'FOUNDER', name='projectaccountstatustype').drop(op.get_bind())
    # ### end Alembic commands ###
