"""user_og_bonus

Revision ID: cc9d4bba7398
Revises: 9686ef605434
Create Date: 2025-06-19 12:47:23.666380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9d4bba7398'
down_revision: Union[str, None] = '9686ef605434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('og_bonus_activated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'og_bonus_activated')
    # ### end Alembic commands ###
