"""post_aura_scores_2

Revision ID: d392e36ecd93
Revises: d8bd4672c2fc
Create Date: 2025-07-22 06:33:22.499026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd392e36ecd93'
down_revision: Union[str, None] = 'd8bd4672c2fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_aura_score_user_id_fkey'), 'post_aura_score', type_='foreignkey')
    op.drop_column('post_aura_score', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_aura_score', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('post_aura_score_user_id_fkey'), 'post_aura_score', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
