"""soc_acc_last_data

Revision ID: d39ba5821566
Revises: cc9d4bba7398
Create Date: 2025-06-24 17:08:33.860210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39ba5821566'
down_revision: Union[str, None] = 'cc9d4bba7398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_account', sa.Column('last_avatar_url', sa.String(), nullable=True))
    op.add_column('social_account', sa.Column('last_followers_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_account', 'last_followers_count')
    op.drop_column('social_account', 'last_avatar_url')
    # ### end Alembic commands ###
