"""remove_templateuserid

Revision ID: dd4ea126bcc8
Revises: 11a8b608d44c
Create Date: 2025-05-29 09:13:21.159961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4ea126bcc8'
down_revision: Union[str, None] = '11a8b608d44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('post_template_user_id_fkey'), 'post_template', type_='foreignkey')
    op.drop_column('post_template', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_template', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('post_template_user_id_fkey'), 'post_template', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
