"""adding_user_credits

Revision ID: f2d356aa8413
Revises: 0a9852091066
Create Date: 2025-05-05 05:35:19.813943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from src.config import settings
from src import utils_base

# revision identifiers, used by Alembic.
revision: str = 'f2d356aa8413'
down_revision: Union[str, None] = '0a9852091066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('credits', sa.Integer(), nullable=True))
    op.execute(f'UPDATE "user" SET credits = {settings.DEFAULT_CREDITS}')
    op.alter_column('user', 'credits', nullable=False)
    op.create_check_constraint('credits_nonnegative', 'user', 'credits >= 0')
    
    op.add_column('user', sa.Column('credits_last_update', sa.Integer(), nullable=True))
    op.execute(f'UPDATE "user" SET credits_last_update = {utils_base.now_timestamp()}')
    op.alter_column('user', 'credits_last_update', nullable=False)



def downgrade() -> None:
    op.drop_column('user', 'credits_last_update')
    op.drop_column('user', 'credits')
    op.drop_constraint('credits_nonnegative', 'user', type_='check')
