"""change_user_chatsettings

Revision ID: f3ef7588323f
Revises: f2d356aa8413
Create Date: 2025-05-05 08:21:28.717171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3ef7588323f'
down_revision: Union[str, None] = 'f2d356aa8413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('user', 'preferred_chat_details_level')
    op.drop_column('user', 'preferred_chat_style')
    op.drop_column('user', 'preferred_chat_model')
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='chatdetailslevel').drop(op.get_bind())
    sa.Enum('FORMAL', 'INFORMAL', name='chatstyle').drop(op.get_bind())
    sa.Enum('GPT_4', 'GPT_4O', 'GPT_4O_MINI', 'GEMINI_2_FLASH', 'GEMINI_2_5_PRO', name='model').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('GPT_4', 'GPT_4O', 'GPT_4O_MINI', 'GEMINI_2_FLASH', 'GEMINI_2_5_PRO', name='model').create(op.get_bind())
    sa.Enum('FORMAL', 'INFORMAL', name='chatstyle').create(op.get_bind())
    sa.Enum('HIGH', 'MEDIUM', 'LOW', name='chatdetailslevel').create(op.get_bind())
    op.add_column('user', sa.Column('preferred_chat_model', postgresql.ENUM('GPT_4', 'GPT_4O', 'GPT_4O_MINI', 'GEMINI_2_FLASH', 'GEMINI_2_5_PRO', name='model', create_type=False), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('preferred_chat_style', postgresql.ENUM('FORMAL', 'INFORMAL', name='chatstyle', create_type=False), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('preferred_chat_details_level', postgresql.ENUM('HIGH', 'MEDIUM', 'LOW', name='chatdetailslevel', create_type=False), autoincrement=False, nullable=True))
    op.drop_column('user', 'chat_settings')
    # ### end Alembic commands ###
